### ISSUE TITLE
Earplug mold should have direction marks

### ISSUE THREAD

**Issue by Joaz** [GliaX/Stethoscope#25]
... to see easily which side is the correct one to bolt it on.

**Comment by tareko** [comment]
@Joaz, any need to revisit this issue? Or shall we leave and close?

**Comment by Joaz** [comment]
Are you actually using that part for production or are you rather using 3rd party earplugs?

**Comment by tareko** [comment]
3rd party. However, it would be nice to leave this option open to those who need it. It sounds like it's not a big enough concern that we should modify this, but rather just close and leave people to sort it out if they use this method.

**Comment by Joaz** [comment]
Yes. This was an annoyance only, it works perfectly without them.
