### ISSUE TITLE
Enhancement request - bill of materials documentation

### ISSUE THREAD

**Issue by MarkRijckenberg** [GliaX/Stethoscope#26]
Hi,

Thanks for sharing this documentation!

A small suggestion: could you please improve the bill of materials section by adding the specific use/purpose, supplier number, order number and price of each bill of material item to make it clearer how much it all costs. Once it becomes visible for everyone, someone might find an alternative supplier that is cheaper with equal or better quality components.....

Here is an example: 

http://labs.nortd.com/lasersaur/bom-one-subsystems-eur

Regards,

Mark Rijckenberg

**Comment by tareko** [comment]
Thank you for this and for the example. I'll try to do a better job with it. Feel free to do it as well if you have the time. The only part with a real supplier here is the Staples folder binder. The rest are generically sourced.

tarek : )

**Comment by MarkRijckenberg** [comment]
I have sent you a pull request :-)

**Comment by tareko** [comment]
Done. I'm now working on adding the staples part (
http://www.staples.ca/en/Staples-Swing-Lock-Report-Cover-Clear-with-Black-Spine-5-Pack/product_780953_2-CA_1_20001
) and will make it into .MD in the readme

**Comment by MarkRijckenberg** [comment]
It would be even better if all those external parts could be replaced with 3D printed parts to lower the total cost. Isn't Picsima Technology or structur3d able to 3D print all the silicone components? I am just wondering....   Examples:   http://www.structur3d.io/#discov3ry   
and    http://www.picsima.com/#!3d-printing-silicone/cjg9

And an alternative to silicone for your components  might be Fila Flex as explained here: https://www.3dhubs.com/talk/thread/silicone-3d-printing      It has a certificate for use in medical situations.   See here:   http://recreus.com/en/4filaflex-filaments        Or maybe you already researched these possibilities?

**Comment by tareko** [comment]
Regarding the silicone, the *mold* is printed. No reason why we can't have an earpiece model, but I think it's more realistic in underfunded situations that they cannot easily switch between filament types (e.g., PLA/ABS to silicone). As such, the mold is printed and silicone (easily available in many places) is injected.

The moldable silicone you included is incorrect and I will ask @Joaz to correct it to what she used.

For now, closing this issue as I included the pull request. If you'd like to pursue the silicone issue further, please start a new issue for it.

tarek : )

**Comment by MarkRijckenberg** [comment]
OK, thanks for the clarifications and sorry about the "moldable silicone" error.
