### ISSUE TITLE
Size of rubber/silicone ring for diaphragm?

### ISSUE THREAD

**Issue by rickybloomfield** [GliaX/Stethoscope#28]
Do you have any specifications for the rubber/silicone ring we should purchase to hold on the diaphragm (similar to the other products you specified)? Thanks!

**Comment by tareko** [comment]
Thank you for commenting @rickybloomfield. I think @Joaz is best to comment, however, here are my thoughts:
Diaphragm should be about 40mm diameter with a middle slit. Total height is about 3mm. Up to now, I have just been grabbing whatever rings are available and testing them, but feel free to try some purchased ones and commenting on them.

tarek : )

**Comment by tareko** [comment]
@rickybloomfield If you have some suggested ring vendors, I could order a variety of rings and test to give my preferred.

tarek : )

**Comment by Joaz** [comment]
I was going to try it out, but with the 5€ on my bank account at the moment, I am unable to source and try different sizes/vendors.

**Comment by rickybloomfield** [comment]
This is why I'm asking - I have no idea where to start for "ring vendors" - it's just not something I've ever had to purchase before. :)

**Comment by tareko** [comment]
Let me think on it. In the meantime, I've used thick rubber bands that are doubled/tripled down. I'll take a photo of that. In looking at how to source from online, I think the terminology is "slotted o ring" or "slotted flat gasket", "square o ring". I see this page that looks most helpful:

http://www.theoringstore.com/index.php?main_page=index&cPath=367_98

Here, they call them "Square Orings also known as Tetraseals® or lathe-cut rings - Buna-N -Duro 70".

Perhaps I can call this group when they are open and check in?

Other examples:
http://www.ecstuning.com/ES1433022/
http://agenaastro.com/ahs-o-ring-2.html

**Comment by rickybloomfield** [comment]
Thanks! A photo would be awesome. I'm planning to construct one of these using parts sourced from the US Amazon store and post my results. I've already ordered the parts I think will work, with the exception of the ring.

**Comment by Joaz** [comment]
I am wondering if it would be possible to cut a groove into standard o-rings to a specific depth. I could rig up the edge of a razor blade using a precisely printed holder to make a cut at a specified depth.

**Comment by rickybloomfield** [comment]
Just curious if you could post that photo? I now have the printed parts from this site and am anxious to assemble. Only other issue is that you mention the T-piece in the instructions, but I don't see it anywhere else. Was that a purchased part?

**Comment by tareko** [comment]
I apologize - I am still travelling and have not yet had a chance. However, here is the T/Y piece:
https://github.com/GliaX/Stethoscope/blob/master/stethoscope_head/output/YPiece_output.stl

I don't like it much myself, and would rather see something like this:
http://www.thingiverse.com/thing:577507 (see last model)

Regarding O-Rings, I called the O ring store, and confirmed that probably the best way to do this with purchased O-Rings is to get the 40mm O-Ring and put a midline slit. I cannot test this for another 4 weeks until I'm back in Canada, but happy to order some your way if you'd like to test it out.

tarek : )

**Comment by rickybloomfield** [comment]
Got it, thanks. I'll print out that piece. I'll also note that the recommended tubes to connect the Y-piece to the ear tubes are way too small. They are the same diameter as the ear tubes themselves, so they don't fit around it. I'll have to order some more of a larger size.

I'd be happy to test the O-rings, but unfortunately I don't have a tool to add the midline slit, which I'd probably need to do it right (i.e., without destroying the O-ring).

Thanks for your help!

**Comment by Joaz** [comment]
@rickybloomfield I have about 2 good ideas for that in my head, need to source new o-rings to make it happen and test it. Feel free to bribe me in order to accelerate that process.

**Comment by tareko** [comment]
@rickybloomfield Please take a look at the [new design of the head](https://github.com/GliaX/Stethoscope/blob/master/head.stl) based on [this commit](https://github.com/GliaX/Stethoscope/commit/a2abf1494062dd74f7cbb66e07adb827aaf49a68) which is expanded on in the [pull request](https://github.com/GliaX/Stethoscope/pull/34).

This will completely denecessitate the o-rings, which we have found hard to source in many parts of the world.

As such, I'm closing this thread as resolved.

tarek : )
