### ISSUE TITLE
Size of Diaphragm

### ISSUE THREAD

**Issue by DaveZA** [GliaX/Stethoscope#33]
Thanks for the design - this is our new home project.

Sorry if this sounds like a dumb question, but nowhere do I see the diameter of the Diaphragm.

Is it supposed to sit inside the lip on the top of the head ?
Does it extend to the inner edge of the ring ?
Should it be glued to the lip, or does it need to have some play between the lip and the ring ?

**Comment by tareko** [comment]
Hi @DaveZA!

Amazing that you've taken an interest in this! Short answer: 40mm diameter.

**However**, before you get too far, please take a look at the [new design of the head](https://github.com/GliaX/Stethoscope/blob/master/head.stl) based on [this commit](https://github.com/GliaX/Stethoscope/commit/a2abf1494062dd74f7cbb66e07adb827aaf49a68) which is expanded on in [this pull request](https://github.com/GliaX/Stethoscope/pull/34).

This will completely denecessitate the o-rings, which we have found hard to source in many parts of the world.

The design is more than good enough to be our default, so I merged it into the master branch today.

Let me know if you have any questions.

tarek : )
