### ISSUE TITLE
Alternative material to Acrylonitrile butadiene styrene plastic?

### ISSUE THREAD

**Issue by abitofalchemy** [GliaX/Stethoscope#36]
What might be the best alternative material to Acrylonitrile butadiene styrene (ABS) plastic?

**Comment by tareko** [comment]
PLA also works well. What is available to you?

**Comment by abitofalchemy** [comment]
Great, PLA is available for all parts except for the eartube, which is only available in "frosted extreme" plastic from shapeways.com. It's due to what their "model checks" that auto determines the material options as the files are uploaded.

**Comment by tareko** [comment]
What are you trying to do? Print through a service like shapeways? perhaps 3dhubs or your local makerspace might be able to help for cheaper? Please do let me know how it works out either way!

tarek : )

**Comment by abitofalchemy** [comment]
I want to build a pair (or two) to bring down to Haiti. I will check out 3dhubs, I hope they can do 100% infill. Yes, I'll let you know how it goes. Thank you!!

**Comment by abitofalchemy** [comment]
Do you have a specific shop on 3dhubs that you were satisfied with the quality of the Head?

**Comment by tareko** [comment]
Two pieces here:
1. Unless you are a physician, please be very cautious about using a stethoscope that has not been built in a proper proper way and tested.

2. We don't have a preferred 3DHubs person, but when you do make a connection, feel free to share this page / my contact information so I can make sure they produce properly.

tarek : )

**Comment by abitofalchemy** [comment]
Tarek,

(BTW if you think I should email you directly instead, let me know)

I am building one for a physician. I went on 3DHubs and found a maker that
can build it, but he cautioned that the 90 deg port (on the Head) could
break if it falls and receives impact. Also he recommended an ABS HighDef
Resin to achieve 100% infill and the added benefit that it will be sturdy.

Another issue raised was the wall thickness of the Head's right-angle port.
If the inner radius is kept as is, the wall can be increased from 1.0mm to
1.5mm, right?

**Comment by tareko** [comment]
I think these conversations are best had in public, so let's continue here.

I don't think you need to worry about the integrity of the port. The part is essentially indestructible (we even did hammer tests), and definitely won't break with a fall. Also, once inside a tube, there is almost zero chance that it fall in a way where that part has to take a load.

Overall, I would suggest printing as is. It hasn't been tested any other way.

tarek : )

**Comment by abitofalchemy** [comment]
Question about the earplug mold. Is it a two piece part? If so what is the upper part for? (the one with holes that go all the way through) 
And, the material for the earplug mold should be hard plastic? It is a mold to be used with "Silicone for ear plugs" so that these earplugs are molded on this earplug_mold.stl part? The earplug model is not meant to be printed in silicon material, right?  // Sal :)

**Comment by tareko** [comment]
This part is no longer needed at this point. You can use any commodity ear piece from low-cost earbuds. Something [like this](https://www.encoredataproducts.com/images/products/secondary/g-er-215-500-1.jpg).
