### ISSUE TITLE
Decide on a license

### ISSUE THREAD

**Issue by pinobatch** [GliaX/Stethoscope#42]
In [this story on SoylentNews about the stethoscope design](https://soylentnews.org/article.pl?sid=18/03/16/0245209), editor "cmn32480" wrote:

>[Ed: as of posting there is no license on the Github documents. Thus as per the Berne Convention it is not yet freely available, until explicitly published under an open license such as CC or similar. ]

Under what license will these plans be made available? The GNU project maintains a [list of licenses for designs of physical objects](https://www.gnu.org/licenses/license-list.en.html#Designs).

**Comment by tareko** [comment]
Hi,

I've added the TAPR OHL, which is the license we always intended. Thank you for pointing out the oversight. As you probably know, copyright does not apply to hardware, and the Berne convention does not apply to this or any hardware. Even its application to design files like SCAD files is tenuous at best. Hardware is usually protected by trade secrets, patents and trademarks, not copyright.

The Open Source Hardware Association has some information on this, as well as some various sources online.

In any case, it was definitely an oversight, as it seemed so obvious to us that it was open source : ) Added and thank you!

tarek : )
